### ISSUE TITLE
支持 UPnP 和 多端口

### ISSUE THREAD

**Issue by sbilly** [Contextualist/acp#1]
主机 A 和 主机 B 在同城不同运营商，网络正常可达。两台机器执行 acp 以后分别报错如下：

```
# 主机 A
rendezvous with 10.x.x.:57xxx | 103.xxx.xxx.1:57xxx
rendezvous timeout for &{laddr:192.168.x.x:38xxx peerLaddr:10.x.x.x:57xxx peerRaddr:103.xxx.xxx.1:57xxx}

# 主机 B
rendezvous with 192.168.x.x:38xxx | 114.x.x.223:38xxx
rendezvous timeout for &{laddr:10.x.x.x:57xxx peerLaddr:192.168.x.x:38xxx peerRaddr:114.x.x.223:38xxx}
```

**Comment by Contextualist** [comment]
对，看上去是打洞失败。有可能是：
- 双方都有针对入站连接的防火墙，或者
- 双方都在对称 NAT (Symmetric NAT) 内

**Comment by sbilly** [comment]
> 双方都有针对入站连接的防火墙

这个是指有配置 DROP 策略么？

**Comment by Contextualist** [comment]
是。如果是公网 IP ，还是需要允许任意高端口的 TCP 入站连接。目前使用的是随机端口，将来计划允许用户设置固定端口。

**Comment by sbilly** [comment]
1. 建议支持一下 UPnP
2. 建议使用两个等效端口，一个端口固定，一个高端口随机

**Comment by Contextualist** [comment]
谢谢提议！

> 1. 建议支持一下 UPnP

UPnP 好像是针对局域网设备发现的。对于目前的实现，如果两台设备都处在同一局域网，会直接使用对方的内网地址连接成功。请问还有怎样的使用场景可以覆盖？

> 2. 建议使用两个等效端口，一个端口固定，一个高端口随机

固定端口后续更新会加的，以覆盖只有特定端口可用的场景。有防火墙的设备应该配置只使用特定的开放端口。

**Comment by sbilly** [comment]
UPnP 是自动在网关上创建一个端口映射，这样有一端支持 UPnP 就能确保 NAT 穿越成功。大量的软路由缺省都是不支持 对称 NAT，但是支持 UPnP。

笔记本等需要移动的设备，固定端口只能在一个特定网络下可用，而移动到其他网络需要使用随机高端口。两个等效端口（一个固定、一个随机高端口）提供了更好的网络兼容性和灵活性。

**Comment by Contextualist** [comment]
谢谢解答！明白了，我去深入了解一下 UPnP。两个等效端口也言之有理。这两个特性可能涉及更改 rendezvous 协议，会放到 0.2.0 版本。

**Comment by sbilly** [comment]
应该不用改协议。就是两个等效端口都尝试打洞，真正传数据只用一个就行了。

**Comment by Contextualist** [comment]
我是指传的数据的格式，之前随便写的没考虑向前兼容，这次会新设计一个 API endpoint 并确保向前兼容。新的数据格式（可能包含 0-2 个端口）会走新的 API endpoint。0.1.x 的客户端继续使用旧的 API endpoint。

**Comment by Contextualist** [comment]
@sbilly 久等了！之前跑去折腾 LLM 了没顾着这边，不过现在这两个功能都实现了。如果你愿意的话，可以试试目前编译出来的 artifact，在这个 PR 的 [CI 运行记录](https://github.com/Contextualist/acp/actions/runs/4550386516)底下可以下载。新协议的服务端还没有正式部署，我先暂时部署在 `https://acp-edge-test.deno.dev` 上，需要在设置里指定一下。我没什么软路由的经验，如果可以还是请你过目一下。没空也没关系，我过几天就正式发布。再次感谢你之前的反馈！
