### ISSUE TITLE
[Suggestion / Fix] Implement error handling

### ISSUE THREAD

**Issue by CozzyBro2** [Contextualist/acp#13]
Hi, hope you're doing well. This issue occurred when I attempted to backup my windows user directory. Acp ran well and transferred about 700MB, then, I got the error you see here:
![image](https://github.com/user-attachments/assets/fbf80860-c4dc-4d1d-b4d3-d5d9c968887e)
ACP did not have access rights to this file, and this one error stopped the entire transfer sequence. This behavior is undesirable when users expect unattended transfers, which is very common many gigabyte transfers. 
Then, my suggestion is to implement error handling; prevent one error from stopping the entire transfer. Thank you

**Comment by Contextualist** [comment]
Yes, logging the error without interrupting the transfer would be a better strategy. I will implement this soon.
