### ISSUE TITLE
dir structure is not preserved while transferring from Windows to Linux

### ISSUE THREAD

**Issue by arctus256** [Contextualist/acp#5]
acp doesn't correctly store files on destination host in case when source and destination are different operating systems.

It is expected that the transferred folder is copy of the source one. however in case when the folder is transferred from windows to linux, the result is rather unexpected. the created hierarchy is flatten and looks like:

drwxr-xr-x 1 arctus wheel 0 Mar 22 22:00  testdir
-rw-rw-rw- 1 arctus wheel 0 Mar 22 22:00 'testdir\t1.txt'
-rw-rw-rw- 1 arctus wheel 0 Mar 22 22:00 'testdir\t2.txt'
-rw-rw-rw- 1 arctus wheel 0 Mar 22 22:00 'testdir\t3.txt'

The problem seems to be the dir separator.

Tested under msys2 and powershell.

**Comment by Contextualist** [comment]
Thanks for reporting! Just pushed the fix. A new version will be released in a week.
